name: omnipro_test
description: Onmi Pro test.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  dartz: ^0.10.1
  another_flushbar: ^1.12.29
  flutter_bloc: ^8.1.2
  mockito: ^5.3.2
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  pull_to_refresh: ^2.0.0
  collection: ^1.17.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/gifs/loading.gif
    - lib/.env