// Mocks generated by Mockito 5.3.2 from annotations
// in omnipro_test/test/home_tests/main_test/home_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:omnipro_test/core/errors/failures.dart' as _i6;
import 'package:omnipro_test/features/home/data/models/retrieve_photos_body.dart'
    as _i8;
import 'package:omnipro_test/features/home/data/models/retrieve_photos_response.dart'
    as _i7;
import 'package:omnipro_test/features/home/domain/repositories/home_repository.dart'
    as _i2;
import 'package:omnipro_test/features/home/domain/usecases/retrieve_api_photos_use_case.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeRepository_0 extends _i1.SmartFake
    implements _i2.HomeRepository {
  _FakeHomeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetApiPhotosUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetApiPhotosUseCase extends _i1.Mock
    implements _i4.GetApiPhotosUseCase {
  MockGetApiPhotosUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get homeRepository => (super.noSuchMethod(
        Invocation.getter(#homeRepository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#homeRepository),
        ),
      ) as _i2.HomeRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.RetrievePhotosResponse>> call(
          _i8.RetrievePhotosBody? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, _i7.RetrievePhotosResponse>>.value(
            _FakeEither_1<_i6.Failure, _i7.RetrievePhotosResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.RetrievePhotosResponse>>);
}
